#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <esp_adc/adc_oneshot.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_3
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_45
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_2
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_46

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_41
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82
#define AUDIO_PA_EN             GPIO_NUM_42

#define STATUS_LED_GPIO         GPIO_NUM_39
#define INIT_LED_GPIO           GPIO_NUM_38
#define BUILTIN_LED_GPIO        GPIO_NUM_5
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH            320
#define DISPLAY_HEIGHT           240
#define DISPLAY_MIRROR_X         true
#define DISPLAY_MIRROR_Y         false
#define DISPLAY_SWAP_XY          true

#define DISPLAY_OFFSET_X         0
#define DISPLAY_OFFSET_Y         0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_33
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define BATTERY_ADC_UNIT    ADC_UNIT_2
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_1

#define CHARGE_ADC_UNIT     ADC_UNIT_1
#define CHARGE_ADC_CHANNEL  ADC_CHANNEL_9


#endif // _BOARD_CONFIG_H_